version: "3.9"
services:
  HardwareDatabase:
    restart: always
    container_name: hardware_database
    image: postgres:latest
    env_file:
      - ./HardwareDatabase/db.env
    ports:
      - "5432:5432"